<div id="menuLeft">
	<h2 class="tabH4_Main">Academic Counseling</h2>
	<ul class="pageletLinks">
		<li><a href="http://www.cerritos.edu/static-html/department-home.htm">Department Home</a></li>
		<li><a href="http://www.cerritos.edu/static-html/department-home-ou.htm">Department Home - OU</a></li>
		<li><a href="http://www.cerritos.edu/static-html/department-inside.htm">Department Inside</a>
			<ul>
				<li><a href="http://www.cerritos.edu/static-html/department-inside2.htm">Department Inside 2</a></li>
				<li><a href="http://www.cerritos.edu/static-html/department-inside2-ou.htm">Department Inside 2 - OU</a></li>
				<li><a href="#">Second Child</a></li>
			</ul>
		</li>
		<li><a href="#">Counseling Appointment</a></li>
		<li><a href="#">New Student Orientation</a></li>
		<li><a href="#">FAQ</a></li>
		<li><a href="#">Education Planning Workshops</a></li>
		<li><a href="#">Student Success Programs</a></li>
		<li><a href="#">Counseling Forms</a></li>
	</ul>
</div>
