<div id="social-wrap">
<div id="social" class="clearfix">
    <div class="col-md-4">
        <h3>Stay Connected</h3>
    </div>
    <div class="col-md-8">
        <div class="social-buttons">
            <section class="mobile-row">
                <a class="social inverse" href="https://www.facebook.com/cerritoscollege/" target="_blank"><i class="fa fa-facebook"></i></a>
                <a class="social inverse" href="https://www.instagram.com" target="_blank"><i class="fa fa-instagram"></i></a>
                <a class="social inverse" href="https://twitter.com/cerritoscollege" target="_blank"><i class="fa fa-twitter"></i></a>
                 <a class="social inverse" href="https://www.youtube.com/channel/UCmQYFzgOkYGPAAfHuNe7mOg" target="_blank"><i class="fa fa-youtube-play"></i></a>
            </section>
        </div>
        <div class="click-throughs">
            <a class="button inverse" href="http://social.pomona.edu" rel="external" target="_blank">Visit Our Social Media Hub</a>
			        </div>
    </div>
</div>
</div>
<div id="footer-wrap">
<div id="footer" class="clearfix">
    <div class="col-xs-5 col-sm-4 col-md-5 info">
		 <div class="col-md-5">
		 <img src="{{f:80150916}}" alt="Cerritos College" class="footer-logo">
			 </div>
		 <div class="col-md-7">
        <p>
            11110 Alondra Blvd.<br/>
            Norwalk, California 90650<br/>
            [<a href ="/map">Campus map</a>]
        </p>
        <p>Phone: <a href="tel:+15628602451">(562) 860-2451</a><br/>
            Emergency: <a href="tel:+15624023674">(562) 402-3674</a><br/><br/>
			<a href="{{d:9121100}}">Campus Police <i class="fa fa-exclamation-triangle"></i></a>
        </p>
			 </div>
		
    </div>
    <div class="col-xs-7 col-sm-8 col-md-7">
        <div class="col-sm-6 col-md-9">
			<h5>Resources</h5>
			<div class="col-md-6">
		
          <a href="/admissions-and-records/catalogue-schedule/">Catalog &amp; Schedule</a>
            <a href="https://ep-secure.cerritos.edu/psp/por91prd/EMPLOYEE/EMPL/h/?tab=PAPP_GUEST" rel="external" class="inverse">MyCerritos</a>
            <a href="https://cerritos.instructure.com/login/canvas" target="_blank" rel="external" class="inverse">Canvas</a>
			<a href="https://orgsync.com/login/cerritos-college" target="_blank" rel="external" class="inverse">OrgSync</a>
            <a href="{{d:9127996}}">Disabled Students <i class="fa fa-wheelchair"></i></a>
				</div>
		<div class="col-md-6">
			<a href="">A-Z Index</a>
			<a href="">News</a>
			<a href="">Events</a>
			<a href="">Directory</a>
			<a href="">Give to Cerritos College</a>
        </div>
        </div>
        <div class="col-sm-6 col-md-3">
			<h5>Get Started</h5>
			<a href="">Apply Now!</a>
            <a href="">Visit Campus</a>
			<a href="">Request Info</a>
			<br />
           Translate
            <div id="google_translate_element"></div><script type="text/javascript">
                function googleTranslateElementInit() {
                    new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false}, 'google_translate_element');
                }
            </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        </div>
    </div>
</div></div>
<a class="back-to-top" href="#"><img alt="Back to Top" title="Back to Top" src="{{f:80150918}}"></a>
