<div id="social-wrap">
<div id="social" class="clearfix">
<div class="col-md-6">
<h3>Stay Connected</h3>
</div>
<div class="col-md-6">
<div class="social-buttons">
<section class="mobile-row"><a class="social inverse" href="https://www.facebook.com/cerritoscollege/" target="_blank"><span class="fa fa-facebook"><span class="sr-only">Facebook</span></span></a> <a class="social inverse" href="https://www.instagram.com/cerritoscollege/" target="_blank"><span class="fa fa-instagram"><span class="sr-only">Instagram</span></span></a> <a class="social inverse" href="https://twitter.com/cerritoscollege" target="_blank"><span class="fa fa-twitter"><span class="sr-only">Twitter</span></span></a> <a class="social inverse" href="https://www.youtube.com/channel/UCmQYFzgOkYGPAAfHuNe7mOg" target="_blank"><span class="fa fa-youtube-play"><span class="sr-only">YouTube</span></span></a></section>
</div>
<!--<div class="click-throughs">
            <a class="button inverse" href="http://social.pomona.edu" rel="external" target="_blank">Visit Our Social Media Hub</a>
			        </div>--></div>
</div>
</div>
<div id="footer-wrap">
<div id="footer" class="clearfix">
<div class="col-xs-5 col-sm-4 col-md-5 info">
<div class="col-md-5"><a title="Cerritos College" href="{{d:9116620}}"><img class="footer-logo" src="{{f:80150937}}" alt="Cerritos College" /></a></div>
<div class="col-md-7">
<p>11110 Alondra Blvd.<br /> Norwalk, California 90650<br /> [<a href="/map">Campus map</a>]</p>
<p>Phone: <a href="tel:+15628602451">(562) 860-2451</a><br /> Emergency: <a href="tel:+15629243618">(562) 924-3618</a><br /><br /> <a href="{{d:9121100}}">Campus Police <span class="fa fa-exclamation-triangle"></span></a></p>
</div>
</div>
<div class="col-xs-7 col-sm-8 col-md-7">
<div class="col-sm-6 col-md-8">
<h4>Resources</h4>
<div class="col-md-6"><a href="mailto:community@cerritos.edu">Contact Us</a> <a class="inverse" href="https://portal.cerritos.edu/" target="_blank">MyCerritos</a> <a href="{{d:9127996}}">Student Accessibility Services</a> <a href="{{f:80068889}}">CARES Act</a> <a href="/campus-guide/abc-index.htm">A-Z Index</a></div>
<!--<a href="/admissions-and-records/catalogue-schedule/">Catalog &amp; Schedule</a>  <a class="inverse" href="https://cerritos.instructure.com/login/canvas" target="_blank" rel="external">Canvas</a> <a class="inverse" href="https://cerritos.campuslabs.com/engage/" target="_blank">FalconSync</a>-->
<div class="col-md-6"><a href="{{d:9122618}}">News</a> <a href="*** Broken d:6237795 https://www.cerritos.edu/calendar/ ***">Events</a> <a href="{{d:9127896}}">Directory</a> <a href="http://cerritoscf.org/" target="_blank">Give to Cerritos College</a> <a class="inverse" href="https://cerritos.campuslabs.com/engage/" target="_blank">FalconSync</a></div>
</div>
<div class="col-sm-6 col-md-4">
<h4>Get Started</h4>
<a href="http://www.cerritos.edu/apply" target="_blank">Apply Now!</a> <!--<a href="/school-relations/programs-and-services/campus-tours.htm">Visit Campus</a> <a href="*** Broken Link ***">Request Info</a>--> <br /> Translate
<!-- <div id="google_translate_element"></div> -->
<!-- <script type="text/javascript">// <![CDATA[
function googleTranslateElementInit() {
                    new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false}, 'google_translate_element');
                }
// ]]></script>
<noscript>Your browser does not support JavaScript!</noscript>
<script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script> -->
<!-- <noscript>Your browser does not support JavaScript!</noscript> -->
	<a class="button" href="https://go.boarddocs.com/ca/cerritos/Board.nsf/Public">Board Agenda</a></div>
</div>
</div>
</div>
<button class="back-to-top" title="Back to Top"><img title="Back to Top" src="{{f:80150918}}" alt="Back to Top" /></button>