<nav id="accessibility" class="accessibility" aria-label="accessibility"><a href="#skiptocontent">Skip to main content</a></nav>
<div id="headerDiv"><nav class="navbar navbar-default" aria-label="navigation bar">
<div class="top-bar">
<div class="container">
	<ul id="nav-audience" class="nav navbar-nav audience">
<li><a href="/get-started/default.htm">Future Students</a></li>
<li><a href="/current-students/default.htm">Current Students</a></li>
<li><a href="/faculty-staff/default.htm">Faculty &amp; Staff</a></li>
<li><a href="/community/default.htm">Community</a></li>
</ul>
	<ul id="quick-links" class="nav navbar-nav navbar-right quick-nav">
<li class="a-z-index"><a href="/campus-guide/abc-index.htm">A-Z Index</a></li>
<li class="dropdown quick-links"><a class="dropdown-toggle" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown">Quick Links &nbsp;<span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a class="external" href="https://cerritos.onbio-key.com/" target="_blank" rel="noopener">MyCerritos</a></li>
<li><a class="external" href="http://www.cerritos.edu/canvas/" target="_blank" rel="noopener">Canvas</a></li>
<li><a href="https://go.boarddocs.com/ca/cerritos/Board.nsf/Public" target="_blank" rel="noopener">BoardDocs</a></li>
<li><a href="/campus-guide/academic-calendar.htm">Academic Calendar</a></li>
<li><a class="external" href="https://cerritos-public.courseleaf.com/" target="_blank" rel="noopener">Catalog</a></li>
<li><a class="external" href="http://www.cerritos.edu/schedule/" target="_blank" rel="noopener">Class Schedule</a></li>
<li><a class="external" href="https://www.bkstr.com/cerritosstore/home/en" target="_blank" rel="noopener">Bookstore</a></li>
<li><a class="external" href="https://libraryguides.cerritos.edu/libraryservices" target="_blank" rel="noopener">Library &amp; Chat</a></li>
<li class="divider" role="separator">&nbsp;</li>
<li><a href="/employees/"><span class="fa fa-phone" aria-hidden="true"><span class="sr-only">Directory</span></span> Faculty &amp; Staff Directory</a></li>
<li><a href="/campus-guide/program-directory/default.htm"><span class="fa fa-sitemap" aria-hidden="true"><span class="sr-only">Sitemap</span></span> Programs and Services Directory</a></li>
<li><a href="https://cerritos.onbio-key.com/"><span class="fas fa-sign-in-alt" aria-hidden="true"><span class="sr-only">Cerritos Portal</span></span> Cerritos Portal</a></li>
<li><a href="/calendar/default.htm"><span class="fa fa-calendar" aria-hidden="true"><span class="sr-only">Cerritos College Calendar</span></span> Cerritos College Calendar</a></li>
<li><a href="/parking/"><span class="fas fa-parking" aria-hidden="true"><span class="sr-only">Parking</span></span> Parking</a></li>
<li><a href="/police/"><span class="fas fa-taxi" aria-hidden="true"><span class="sr-only">Safety</span></span> Campus Safety</a></li>
</ul>
</li>
	
	
	
<li id="button-apply" class="dropdown quick-links"><a class="dropdown-toggle apply-now" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown">Apply Now&nbsp;<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><a href="https://www.cerritos.edu/apply" target="_blank" rel="noopener">Student Application</a></li>
		<li><a href="https://intl.opencccapply.net/gateway/intl?cccMisCode=811" target="_blank" rel="noopener">International Student Application</a></li>
	</ul>
</li>
	
	
	
<li id="button-give"><a class="give" href="http://cerritoscf.org/" target="_blank" rel="noopener"><!--<span class="fa fa-gift" aria-hidden="true"><span class="sr-only">Give</span></span>-->Give</a></li>
<li id="button-map"><a class="campus-map" href="/campus-guide/default.htm">Campus Maps</a></li>
</ul>
	
</div>
</div>
<div class="container">
	
<div class="navbar-header">
<h1>Cerritos College<a class="navbar-brand logo" title="College Home" href="/"><img title="Cerritos College, Norwalk California" src="/_resources/images/common/cerritos-college-logo.svg" alt="Cerritos College, Norwalk California" /></a></h1>
	
<ul class="mobile mobile-quicklinks">
<li><a href="/campus-guide/abc-index.htm"> <span class="big">A-Z</span> <span class="small">Index</span> </a></li>
<li><a title="Directory" href="/employees/"><span class="fa fa-phone" aria-hidden="true"><span class="sr-only">Faculty &amp; Staff Directory</span></span></a></li>
<li><a title="Calendar" href="/calendar/default.htm"><span class="fa fa-calendar" aria-hidden="true"><span class="sr-only">Cerritos College Calendar</span></span></a></li>
<li class="dropdown search"><a class="dropdown-toggle" title="Search" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown"><span class="fa fa-search" aria-hidden="true"><span class="sr-only">Search</span></span></a>
<ul class="dropdown-menu">
<li><!--<form id="searchForm" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
<div class="form-group">
<input class="form-control" placeholder="Search" name="q" id="q" aria-lable="search" type="text">
</div>
</form>--> <!--Mobile Search--> <!--
<script>

(function() {
var cx = '008525147052714186440:tkcmuqghz4s';
var gcse = document.createElement('script');
gcse.type = 'text/javascript';
gcse.async = true;
gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(gcse, s);
})();


</script>
<gcse:searchbox-only resultsUrl="/campus-guide/search.htm"></gcse:searchbox-only>
-->
<div class="w-form form-wrapper"><form id="searchbox-mobile" action="/campus-guide/search.htm" method="get" name="cse"><input name="cx" type="hidden" value="your-008525147052714186440:tkcmuqghz4s" /> <input name="ie" type="hidden" value="utf-8" /> <input name="hl" type="hidden" value="en" /> <label for="q-mobile">Search:&nbsp;</label><input id="q-mobile" name="q" type="text" /> <input name="sa" type="submit" value="Go" /></form></div>
</li>
</ul>
</li>
<li><a href="https://www-cerritos-edu.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp"><span class="fa-solid fa-language"><span class="sr-only">Translate</span></span></a></li>	
</ul>
	
<ul class="mobile mobile-quicklinks dropdown">
<li class="dropdown quick-links"><a class="dropdown-toggle" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown">Quick Links </a>
<ul class="dropdown-menu">
<li><a class="external" href="https://cerritos.onbio-key.com/" target="_blank" rel="noopener">MyCerritos</a></li>
<li><a class="external" href="http://www.cerritos.edu/canvas/" target="_blank" rel="noopener">Canvas</a></li>
<li><a href="https://go.boarddocs.com/ca/cerritos/Board.nsf/Public" target="_blank" rel="noopener">BoardDocs</a></li>
<li><a href="/campus-guide/academic-calendar.htm">Academic Calendar</a></li>
<li><a class="external" href="https://cerritos-public.courseleaf.com/" target="_blank" rel="noopener">Catalog</a></li>
<li><a class="external" href="http://www.cerritos.edu/schedule/" target="_blank" rel="noopener">Class Schedule</a></li>
<li><a class="external" href="https://www.bkstr.com/cerritosstore/home/en" target="_blank" rel="noopener">Bookstore</a></li>
<li><a class="external" href="https://libraryguides.cerritos.edu/libraryservices" target="_blank" rel="noopener">Library &amp; Chat</a></li>
<li class="divider" role="separator">&nbsp;</li>
<li><a href="/employees/"><span class="fas fa-phone" aria-hidden="true"><span class="sr-only">Directory</span></span> Faculty &amp; Staff Directory</a></li>
<li><a href="/campus-guide/program-directory/default.htm"><span class="fas fa-sitemap" aria-hidden="true"><span class="sr-only">Sitemap</span></span> Programs and Services Directory</a></li>
<li><a href="https://cerritos.onbio-key.com/"><span class="fas fa-sign-in-alt" aria-hidden="true"><span class="sr-only">Cerritos Portal</span></span> Cerritos Portal</a></li>
<li><a href="/calendar/default.htm"><span class="fas fa-calendar" aria-hidden="true"><span class="sr-only">Cerritos College Calendar</span></span> Cerritos College Calendar</a></li>
<li><a href="/parking/"><span class="fas fa-parking" aria-hidden="true"><span class="sr-only">Parking</span></span> Parking</a></li>
<li><a href="/police/"><span class="fas fa-taxi" aria-hidden="true"><span class="sr-only">Safety</span></span> Campus Safety</a></li>
</ul>
</li>
</ul>
<a class="navbar-toggle" role="button" href="#siteNavigation" data-target="#siteNavigation">
<div class="bars">&nbsp;</div>
<div class="text">Menu</div>
</a></div>
<div id="siteNavigation" class="siteNavigation"><a class="menuClose visible-md visible-sm visible-xs" href="#"><span class="sr-only">Close</span></a>
<ul class="nav navbar-nav main-nav">
<li id="button-apply-2" class="hidden-lg"><a class="apply-now" href="/apply" target="_blank" rel="noopener">Student Application</a></li>
<li id="button-apply-intl" class="hidden-lg"><a class="apply-now" href="https://intl.opencccapply.net/gateway/intl?cccMisCode=811" target="_blank" rel="noopener">International Student Application</a></li>
<li class="hidden-lg"><a class="apply-now" href="http://cerritoscf.org/" target="_blank" rel="noopener">Make a Gift</a></li>
<li class="hidden-lg"><a class="apply-now" href="/campus-guide/default.htm">Campus Maps</a></li>
<li><a href="/about/default.htm">About</a></li>
<li><a href="/admissions-and-records/default.htm">Admissions</a></li>
<li><a href="/financial-aid/default.htm">Financial Aid</a></li>
<li><a href="/academics/default.htm">Academics</a></li>
<li><a href="/services/default.htm">Services &amp; Support </a></li>
<!--<li><a href="/caring-campus/default.htm"><span class="fa fa-heart" aria-hidden="true"></span> We Care</a></li>-->
	
	
	
	
<li class="hidden-lg audience-mobile"><a href="/get-started/default.htm">Future Students</a></li>
<li class="hidden-lg audience-mobile"><a href="/current-students/default.htm">Current Students</a></li>
<li class="hidden-lg audience-mobile"><a href="/faculty-staff/default.htm">Faculty &amp; Staff</a></li>
<li class="hidden-lg audience-mobile"><a href="/community/default.htm">Community</a></li>
<li class="dropdown search"><a class="dropdown-toggle" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown"> <span class="fa fa-search" aria-hidden="true"><span class="sr-only">Search</span></span></a>
<ul class="dropdown-menu">
<li><!--<form id="searchForm-2" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
<div class="form-group">
<input name="q-2" id="q-2" class="form-control" placeholder="Search" aria-lable="search" type="text">
</div>
</form>
--> <!--
<script>
function() {
var cx = '008525147052714186440:tkcmuqghz4s';
var gcse = document.createElement('script');
gcse.type = 'text/javascript';
gcse.async = true;
gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(gcse, s);
}();
</script>
<gcse:searchbox-only resultsUrl="/campus-guide/search.htm"></gcse:searchbox-only>
-->
<div class="w-form form-wrapper"><form id="searchbox-desktop" action="/campus-guide/search.htm" method="get" name="cse"><input name="cx" type="hidden" value="your-008525147052714186440:tkcmuqghz4s" /> <input name="ie" type="hidden" value="utf-8" /> <input name="hl" type="hidden" value="en" /> <label for="q-desktop">Search Site:&nbsp;</label><input id="q-desktop" name="q" type="text" /> <input name="sa" type="submit" value="Go" /></form></div>
</li>

</ul>

</li>
	
	<li class="google_translate">
		<div id="google_translate_element"></div>
<script type="text/javascript">// <![CDATA[
function googleTranslateElementInit() {
                    new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.VERTICAL, autoDisplay: false}, 'google_translate_element');
	
	var $googleDiv = $("#google_translate_element .skiptranslate");
var $googleDivChild = $("#google_translate_element .skiptranslate div");
$googleDivChild.next().remove();

$googleDiv.contents().filter(function(){
return this.nodeType === 3 && $.trim(this.nodeValue) !== '';
}).remove();
	
	
                }
// ]]></script>
<noscript>Your browser does not support JavaScript!</noscript>
<script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<noscript>Your browser does not support JavaScript!</noscript>
	</li>

	
	
</ul>
</div>
</div>
</nav>
</div>

<!--#include virtual="/ou-alerts/alerts-config.css.html" -->