<nav class="accessibility" id="accessibility">
     <a href="#skiptocontent">Skip to content</a>
	<a href="#skiptonavigation">Skip to section navigation and content info</a>
</nav>
<div id="headerDiv">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <h1>Cerritos College<a class="navbar-brand logo" href="{{d:9116620}}"><img alt="Cerritos College, Norwalk California" title="Cerritos College, Norwalk California" src="{{f:80150916}}" /></a></h1>
            <ul class="mobile mobile-quicklinks">
                <li>
                    <a href="/campus-guide/abc-index.htm">
                        <span class="big">A-Z</span> <span class="small">Index</span>
                    </a>
                </li>
                <li>
                    <a href="{{d:9127896}}"><i aria-hidden="true" class="fa fa-phone"></i></a>
                </li>
                <li>
                    <a href="*** Broken Link ***"><i aria-hidden="true" class="fa fa-calendar"></i></a>
                </li>
                <li class="dropdown search">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"><i aria-hidden="true" class="fa fa-search"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <form id="searchForm" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
                                <div class="form-group">
                                    <input class="form-control" placeholder="Search" type="text" name="q" id="q" aria-lable="search" />
                                </div>
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
			<ul class="mobile mobile-quicklinks dropdown">
                <li class="dropdown quick-links">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Quick Links <i class="fa fa-caret-down fa-lg"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Link Here</a>
                        </li>
                        <li><a href="#">Link Here</a>
                        </li>
                        <li><a href="http://cert.ent.sirsi.net/client/en_US/cerritos/" target="_blank">Library</a>
                        </li>
                        <li><a href="#">Link Here</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <a class="navbar-toggle" data-target="#siteNavigation" role="button" href="#siteNavigation">
                <div class="bars">
                    <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                </div>
                <div class="text">
                    Menu
                </div>
            </a>
        </div>
		<div class="siteNavigation" id="siteNavigation">
           <a href="#" class="menuClose visible-md visible-sm visible-xs"><i class="fa fa-times" aria-hidden="true"></i><span class="sr-only">Close</span></a>
            <ul class="nav navbar-nav main-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Admissions &amp; Aid</a>
                </li>
                <li>
                    <a href="#">Academics</a>
                </li>
                <li>
                    <a href="#">Student Life</a>
                </li>
                <li>
                    <a href="#">Resources</a>
                </li>
            </ul>
            
			
            <ul class="nav navbar-nav navbar-right quick-nav" id="quick-links">
				<li class="a-z-index"><a href="/campus-guide/abc-index.htm">A-Z Index</a></li>
                <li class="dropdown quick-links">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Quick Links <i class="fa fa-caret-down fa-lg"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Link Here</a>
                        </li>
                        <li>
                            <a href="#">Link Here</a>
                        </li>
                        <li>
                            <a href="http://cert.ent.sirsi.net/client/en_US/cerritos/" target="_blank">Library</a>
                        </li>
                        <li>
                            <a href="#">Link Here</a>
                        </li>
                        <li class="divider" role="separator"></li>
                        <li>
                            <a href="{{d:9127896}}"><i aria-hidden="true" class="fa fa-phone"></i> Directory</a>
                        </li>
                        <li>
                            <a href="*** Broken Link ***"><i aria-hidden="true" class="fa fa-calendar"></i> Calendar</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown search">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"><i aria-hidden="true" class="fa fa-search"></i></a>
                    <ul class="dropdown-menu">
                        <li>
							<form id="searchForm" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
                                <div class="form-group">
                                    <input name="q" id="q" class="form-control" placeholder="Search" aria-lable="search" type="text"/>
                                </div>
                            </form>
                        </li>
                    </ul>
                </li>
				
				
                <li id="button-apply">
                    <a class="apply-now" href="/apply" target="_blank">Apply Now!</a>
                </li>
            </ul>
  
        <ul class="nav navbar-nav audience" id="nav-audience">
            <li>
                <a href="#">Future Students</a>
            </li>
            <li>
                <a href="#">Current Students</a>
            </li>
            <li>
                <a href="{{d:9127896}}">Faculty &amp; Staff</a>
            </li>
            <li>
                <a href="#">Community</a>
            </li>
        </ul>
        </div>
    </nav>
</div>
