<nav class="accessibility" id="accessibility">
  <ul>
    <li id="skip-secnav"><a href="#skiptonavigation">Skip to section navigation</a></li>
    <li id="skip-content"><a href="#skiptocontent">Skip to content</a></li>
    
  </ul>
</nav>
<div id="headerDiv">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <h1>Cerritos College<a class="navbar-brand logo" href="{{d:9116620}}"><img alt="Cerritos College, Norwalk California" title="Cerritos College, Norwalk California" src="{{f:80150916}}"></a></h1>
            <ul class="mobile mobile-quicklinks">
                <li>
                    <a href="/campus-guide/abc-index.htm">
                        <span class="big">A-Z</span><br/>
                        <span class="small">Index</span>
                    </a>
                </li>
                <li>
                    <a href="/campus-guide/employees.htm"><i aria-hidden="true" class="fa fa-phone"></i></a>
                </li>
                <li>
                    <a href="*** Broken Link ***"><i aria-hidden="true" class="fa fa-calendar"></i></a>
                </li>
                <li>
                    <a href="/campus-guide/search.htm"><i aria-hidden="true" class="fa fa-search"></i></a>
                </li>
            </ul>
            <button class="navbar-toggle" data-target="#navCollapse" data-toggle="collapse" type="button">
                <div class="bars">
                    <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                </div>
                <div class="text">
                    Menu
                </div>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navCollapse">
            <ul class="nav navbar-nav main-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Admissions &amp; Aid</a>
                </li>
                <li>
                    <a href="#">Academics</a>
                </li>
                <li>
                    <a href="#">Student Life</a>
                </li>
                <li>
                    <a href="#">Resources</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right quick-nav" id="quick-links">
                <li class="dropdown quick-links">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Quick Links</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Link Here</a>
                        </li>
                        <li>
                            <a href="#">Link Here</a>
                        </li>
                        <li>
                            <a href="http://cert.ent.sirsi.net/client/en_US/cerritos/" target="_blank">Library</a>
                        </li>
                        <li>
                            <a href="#">Link Here</a>
                        </li>
                        <li class="divider" role="separator"></li>
                        <li>
                            <a href="/campus-guide/abc-index.htm">A-Z Index</a>
                        </li>
                        <li>
                            <a href="/campus-guide/employees.htm"><i aria-hidden="true" class="fa fa-phone"></i> Directory</a>
                        </li>
                        <li>
                            <a href="*** Broken Link ***"><i aria-hidden="true" class="fa fa-calendar"></i> Calendar</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown search">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"><i aria-hidden="true" class="fa fa-search"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <form id="searchForm" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
                                <div class="form-group">
                                    <input name="q" id="q" class="form-control" placeholder="Search" type="text"/>
									<input type="submit" value="Go"/>
                                </div>
                            </form>
                        </li>
                    </ul>
                </li>
                <li id="button-apply">
                    <a class="apply-now" href="https://www.opencccapply.net/uPortal/render.userLayoutRootNode.uP;jsessionid=CBE357F453BC5CBB6501D3C0636DC7EB" target="_blank">Apply Now</a>
                </li>
            </ul>
        </div>
        <ul class="nav navbar-nav audience" id="nav-audience">
            <li>
                <a href="#">Future Students</a>
            </li>
            <li>
                <a href="#">Current Students</a>
            </li>
            <li>
                <a href="/campus-guide/faculty.htm">Faculty &amp; Staff</a>
            </li>
            <li>
                <a href="#">Community</a>
            </li>
        </ul>
    </nav>
</div>
