<table class="ou-block-grid-three-up" style="width: 100%;">
	<caption>Block Grid - Three Columns</caption>
	<tbody>
		<tr class="heading">
			<td  colspan="3">
				<h3>Enter Heading Here</h3>
			</td>
		</tr>
		<tr class="content">
			<td class="thirty">
				<p>Enter Content Here</p>
			</td>
			<td class="thirty">
				<p>Enter Content Here</p>
			</td>
			<td class="thirty">
				<p>Enter Content Here</p>
			</td>
		</tr>
	</tbody>
</table>