<table class="ou-block-grid-four-up" style="width: 100%;">
	<caption>Block Grid - Four Columns</caption>
	<tbody>
		<tr class="heading">
			<td  colspan="4">
				<h3>Enter Heading Here</h3>
			</td>
		</tr>
		<tr class="content">
			<td class="twenty-five">
				<p>Enter Content Here</p>
			</td>
			<td class="twenty-five">
				<p>Enter Content Here</p>
			</td>
			<td class="twenty-five">
				<p>Enter Content Here</p>
			</td>
			<td class="twenty-five">
				<p>Enter Content Here</p>
			</td>
		</tr>
	</tbody>
</table>
