<table class="ou-button-centered" style="width: 100%;">
	<caption>Centered Button</caption>
	<thead>
		<tr>
			<th class="ou-help thirty-three">Button Size</th>
			<th class="ou-help thirty-three">Button Color</th>
			<th class="ou-help thirty-three">Button Style</th>
		</tr>
		<tr class="options">
			<th class="size">small</th>
			<th class="color">theme</th>
			<th class="radius">none</th>
		</tr>
	</thead>
	<tbody>		
		<tr class="content"><td style="text-align:center;" colspan="3"><a href="#">Button Link</a></td></tr>
	</tbody>
</table>