<table class="ou-panel-two-column-flex" style="width: 100%;">
	<caption>Panel Two Column - Flexible Width</caption>
	<thead>
		<tr class="options">
			<th class="thirty-three">4</th>
			<th class="thirty-three">8</th>
			<th class="thirty-three">theme</th>
		</tr>
		<tr>
			<th class="ou-help" colspan="3"><em>Panel Color Options: theme, grey, blue, red, green, dgrey <br />Note: Total width of above columns must equal 12. <br />Example: 6 and 6, 4 and 8, etc.</em></th>
		</tr>
	</thead>
	<tbody>
		<tr class="heading">
			<td colspan="3">
				<h3>Enter Heading Here</h3>
			</td>
		</tr>
		<tr class="content">
			<td colspan="2">
				<p>Enter Content Here</p>
			</td>
			<td>
				<p>Enter Content Here</p>
			</td>
		</tr>
	</tbody>
</table>