<table class="ou-two-column-flex" style="width: 100%;">
			<caption>Two Column - Flexible Width</caption>
	<thead>
		<tr class="width">
			<th class="fifty">4</th>
			<th class="fifty">8</th>
		</tr>
		<tr>
			<th class="ou-help" colspan="2"><em>Note: Total width of both columns above must equal 12. <br/>Example: 6 and 6, 4 and 8, etc.</em></th>
		</tr>
	</thead>
	<tbody>
		<tr class="heading">
			<td colspan="2">
				<h3>Enter Heading Here</h3>
			</td>
		</tr>
		<tr class="content">
			<td>
				<p>Enter Content Here</p>
			</td>
			<td>
				<p>Enter Content Here</p>
			</td>
		</tr>
	</tbody>
</table>