	<div class="department-names-left">
		<ul>
		<li><a class="button" href="#">Automotive Collision Repair</a></li>
		<li><a class="button" href="#">Automotive Mechanical Repair</a></li>
		<li><a class="button" href="#">Cosmetology</a></li>
		<li><a class="button" href="#">Engineering Design Technology</a></li>
		<li><a class="button" href="#">Engineering Technology</a></li>
		<li><a class="button" href="#">Industrial Arts</a></li>
		</ul>
	</div>
	<div class="department-names-right">
	<ul><li><a class="button" href="#">Manufacturing Technology</a></li>
		<li><a class="button" href="#">New Product Development</a></li>
		<li><a class="button" href="#">Plastics &amp; Composites</a></li>
		<li><a class="button" href="#">Welding</a></li>
		<li><a class="button" href="#">Woodworking Manufacturing</a></li></ul>
	</div>
