
<!-- Put the end close of this comment at the end of the complete code to comment out the Alert. Put it baack at the end of the comment to activate the Alert. -->
<div id="emergencyNotice">
	<div class="WhiteInfo"><!-- Use thses classes for the level of alert: RedAlert, YellowWarning, BlueInfo, or WhiteInfo-->
        <div class="right pointer"><img class="close-icon" alt="x" src="{{f:80150862}}" />
		</div>  
		<i class="fa fa-exclamation-triangle"></i>
            <p>Safety Alert!!!</p>
    </div>
</div>
