<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"><!-- Bootstrap 5.3.8 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css"><!-- Swiper 12 -->

<link rel="stylesheet" href="/_resources/fonts/fontawesome-free-6.4.2-web/css/all.min.css"><!-- /_resources/fonts/fontawesome-free-6.4.2-web/css/all.min.css-->

<!-- Load fonts from Google Fonts CDN -- 10/27/2023 - Open Sans and Roboto Condensed -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;0,700;0,800;1,400;1,600;1,700;1,800&family=Roboto+Condensed:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" crossorigin="anonymous">

<link rel="stylesheet" href="/_resources/css/flexslider.css" type="text/css"><!-- /_resources/css/flexslider.css -->
<link rel="stylesheet" href="/_resources/css/legacy.css"/><!-- /_resources/css/legacy -->
<link rel="stylesheet" href="/_resources/css/owl.carousel.css"><!-- /_resources/css/owl.carousel.css-->
<link rel="stylesheet" href="/_resources/css/owl.theme.default.min.css"><!-- /_resources/css/owl.theme.default.min.css -->
<link rel="stylesheet" href="/_resources/css/aos_css_reduced_motion.css"/><!-- /_resources/css/aos_css_reduced_motion.css  -->
<link rel="stylesheet" href="/_resources/css/components.css"/> <!--/_resources/css/components.css  -->
<link rel="stylesheet" href="/_resources/css/modern-campus-forms.css"/> <!--/_resources/css/modern-campus-forms.css  -->
<link rel="stylesheet" href="/_resources/css/cerritos-bootstrap.css"/><!-- /_resources/css/cerritos-bootstrap.css -->
