<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"><!-- Bootstrap 5.3.8 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css"><!-- Swiper 12 -->

<!-- Font Awesome -->
<link rel="stylesheet" href="/_resources/fonts/font-awesome-6-pro/css/fontawesome.min.css"><!-- /_resources/fonts/font-awesome-6-pro/css/fontawesome.min.css -->
<link rel="stylesheet" href="/_resources/fonts/font-awesome-6-pro/css/brands.min.css"><!-- /_resources/fonts/font-awesome-6-pro/css/brands.min.css -->
<link rel="stylesheet" href="/_resources/fonts/font-awesome-6-pro/css/regular.min.css"><!-- /_resources/fonts/font-awesome-6-pro/css/regular.min.css -->
<link rel="stylesheet" href="/_resources/fonts/font-awesome-6-pro/css/solid.min.css"><!-- /_resources/fonts/font-awesome-6-pro/css/solid.min.css -->
<link rel="stylesheet" href="/_resources/fonts/font-awesome-6-pro/css/sharp-regular.min.css"><!-- /_resources/fonts/font-awesome-6-pro/css/sharp-regular.min.css -->
<link rel="stylesheet" href="/_resources/fonts/font-awesome-6-pro/css/sharp-solid.min.css"><!-- /_resources/fonts/font-awesome-6-pro/css/sharp-solid.min.css -->

<!-- Load fonts from Google Fonts CDN Poppins and Karla -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

<!-- Legacy -->
<link rel="stylesheet" href="/_resources/css/flexslider.css" type="text/css"><!-- /_resources/css/flexslider.css -->
<link rel="stylesheet" href="/_resources/css/legacy.css"/><!-- /_resources/css/legacy -->
<link rel="stylesheet" href="/_resources/css/owl.carousel.css"><!-- /_resources/css/owl.carousel.css-->
<link rel="stylesheet" href="/_resources/css/owl.theme.default.min.css"><!-- /_resources/css/owl.theme.default.min.css -->
<link rel="stylesheet" href="/_resources/css/components.css"/> <!--/_resources/css/components.css  -->
<link rel="stylesheet" href="/_resources/css/modern-campus-forms.css"/> <!--/_resources/css/modern-campus-forms.css  -->

<!-- Custom Override for BS -->
<link rel="stylesheet" href="/_resources/css/cerritos-bootstrap.css"/><!-- /_resources/css/cerritos-bootstrap.css -->

<!-- Custom CSS for Cerritos -->
<link rel="stylesheet" href="/_resources/css/cerritos.css"/><!-- /_resources/css/cerritos.css -->

