
<div id="deptinfo">
<hr />
	<div>
        <h3><i class="fa fa-phone-square fa-lg"></i> Contact Us</h3>
        <p><a href="tel:15628602451">(562) 860-2451 ext 2231</a></p>
        <p><a href="#">Review Appointment Policy and Hours</a></p>
    </div>
<hr />
    <div>
        <h3><i class="fa fa-map-marker fa-lg"></i> Location</h3>
        <p>Administration Bldg (off of Alondra Blvd.)</p>
        <p><a href="#">[map]</a></p>
    </div>
<hr />
	 <div>
        <h3><i class="fa fa-link fa-lg"></i> Related Links</h3>
		 <p><a href="test.pdf">PDF Link Here</a></p>
        <p><a href="#" rel="external">External Link Here</a></p>
    </div>
</div>
