<div id="social-wrap">
<div id="social" class="clearfix">
<div class="col-md-6">
<h3>Stay Connected</h3>
</div>
<div class="col-md-6">
<div class="social-buttons">
<section class="mobile-row">
	<a class="social inverse" title="Facebook" href="https://www.facebook.com/cerritoscollege/" target="_blank" rel="noopener"><span class="fa-brands fa-facebook-f"><span class="sr-only">Facebook</span></span></a> 
	
	<a class="social inverse" title="Instagram" href="https://www.instagram.com/cerritoscollege/" target="_blank" rel="noopener"><span class="fa-brands fa-instagram"><span class="sr-only">Instagram</span></span></a> 
	
	<a class="social inverse" title="TikTok" href="https://www.tiktok.com/@cerritoscollege" target="_blank" rel="noopener"><span class="fa-brands fa-tiktok"><span class="sr-only">TikTok</span></span></a>
	
	<a class="social inverse" title="Twitter/X" href="https://twitter.com/cerritoscollege" target="_blank" rel="noopener"><span class="fa-brands fa-x-twitter"><span class="sr-only">Twitter/X</span></span></a> 
	
	<a class="social inverse" title="YouTube" href="https://www.youtube.com/channel/UCmQYFzgOkYGPAAfHuNe7mOg" target="_blank" rel="noopener"><span class="fa-brands fa-youtube"><span class="sr-only">YouTube</span></span></a>
	
	</section>
</div>
<!--<div class="click-throughs">
            <a class="button inverse" href="http://social.pomona.edu" rel="external" target="_blank">Visit Our Social Media Hub</a>
			        </div>--></div>
</div>
</div>
<div id="footer-wrap">
<div id="footer" class="clearfix" role="navigation">
<div class="col-xs-5 col-sm-4 col-md-5 info">
<div class="col-md-5"><a title="Cerritos College" href="{{d:9116620}}"><img class="footer-logo" src="{{f:80150937}}" alt="Cerritos College" /></a></div>
<div class="col-md-7">
<p>11110 Alondra Blvd.<br />Norwalk, California 90650<br />[<a href="/map">Campus map</a>]</p>
<p>Phone: <a href="tel:+15628602451">(562) 860-2451</a><br />Emergency: <a href="tel:+15629243618">(562) 924-3618</a><br /><br /><a href="{{d:9121100}}">Police Department <span class="fa fa-exclamation-triangle"></span></a></p>
</div>
</div>
<div class="col-xs-7 col-sm-8 col-md-7">
<div class="col-sm-6 col-md-8">
<h4>Resources</h4>
<div class="col-md-6"><a href="{{f:80276509}}">Contact Us</a> <a class="inverse" href="https://portal.cerritos.edu/" target="_blank" rel="noopener">MyCerritos</a> <a href="{{d:9127996}}">Student Accessibility Services</a> <a href="{{f:80068889}}">CARES Act</a> <a href="{{f:80069408}}">Title-IX &amp;&nbsp;Discrimination</a></div>
<!--<a href="/admissions-and-records/catalogue-schedule/">Catalog &amp; Schedule</a>  <a class="inverse" href="https://cerritos.instructure.com/login/canvas" target="_blank" rel="external">Canvas</a> <a class="inverse" href="https://cerritos.campuslabs.com/engage/" target="_blank">FalconSync</a>-->
<div class="col-md-6"><a href="/campus-guide/abc-index.htm">A-Z Index</a> <a href="{{d:9122618}}">News</a> <a href="/calendar/default.htm">Events</a> <a href="{{d:9127896}}">Directory</a> <a href="http://cerritoscf.org/" target="_blank" rel="noopener">Give to Cerritos College</a> <a class="inverse" href="https://cerritos.campusgroups.com/home_login" target="_blank" rel="noopener">FalConnect</a></div>
</div>
<div class="col-sm-6 col-md-4">
<h4>Get Started</h4>
<a href="/apply" target="_blank" rel="noopener">Apply Now!</a> <!--<a href="/school-relations/programs-and-services/campus-tours.htm">Visit Campus</a> <a href="*** Broken Link ***">Request Info</a>--> <br />Translate
<div id="google_translate_element"></div>
<script type="text/javascript">// <![CDATA[
function googleTranslateElementInit() {
                    new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.VERTICAL, autoDisplay: false}, 'google_translate_element');
                }
// ]]></script>
<noscript>Your browser does not support JavaScript!</noscript>
<script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<noscript>Your browser does not support JavaScript!</noscript><a class="button" href="https://go.boarddocs.com/ca/cerritos/Board.nsf/Public">Board Agenda</a></div>
</div>
</div>
</div>
<div><button class="back-to-top" title="Back to Top"><img title="Back to Top" src="{{f:80150918}}" alt="Back to Top" /></button></div>
<!--#include virtual="/ou-alerts/alerts-config.alerts.html" -->

<!-- scripts moved from <head> to footer 10/27/2023 -->
<script src="{{f:80151164}}"></script>
<script src="{{f:80151169}}"></script>
<script src="{{f:80151144}}"></script>
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58dc7d749801000011c55022&product=inline-share-buttons"></script>

<script type="module" data-eab-app="kbi">
		

import portal from "https://cdn.eab.com/portal/1.1.0/index.js";
 
const frame = portal.startup({
  host: "https://cdn.eab.com/navai/",
  render_to: `[data-eab-app="kbi"]`,
  remote_view: "run_plan",
  environment: "run_plan_prod",
  settings: {
    token: "2d1bd520-1feb-4b0b-8cdf-9e7650f1394a",
    partner_name: "cerritos",
    environment: "prod",
    button_color: "#00355F"
  },
});


</script>