<nav id="accessibility" class="accessibility"><a href="#skiptocontent">Skip to main content</a></nav>
<div id="headerDiv">
	<nav class="navbar navbar-default">
		<div class="top-bar">
			<div class="container">
				<ul id="nav-audience" class="nav navbar-nav audience">
					<li><a href="/get-started/default.htm">Future Students</a></li>
					<li><a href="{{f:80147106}}">Current Students</a></li>
					<li><a href="{{f:80267046}}">Faculty &amp; Staff</a></li>
					<li><a href="{{f:80270022}}">Community</a></li>
				</ul>
				<ul id="quick-links" class="nav navbar-nav navbar-right quick-nav">
					<li class="a-z-index"><a href="/campus-guide/abc-index.htm">A-Z Index</a></li>
					<li class="dropdown quick-links"><a class="dropdown-toggle" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown">Quick Links </a>
						<ul class="dropdown-menu">
							<li><a class="external" href="https://cerritos.onbio-key.com/" target="_blank">MyCerritos</a></li>
							<li><a class="external" href="http://www.cerritos.edu/canvas/" target="_blank">Canvas</a></li>
							<li><a href="https://go.boarddocs.com/ca/cerritos/Board.nsf/Public" target="_blank">BoardDocs</a></li>
							<li><a href="/campus-guide/academic-calendar.htm">Academic Calendar</a></li>
							<li><a href="https://www.cerritos.edu/admissions-and-records/catalogue-schedule/default.htm">Catalog &amp; Schedule</a></li>
							<li><a class="external" href="http://www.cerritos.edu/schedule/" target="_blank">Schedule Plus</a></li>
							<li><a class="external" href="https://www.bkstr.com/cerritosstore/home/en" target="_blank">Bookstore</a></li>
							<li><a class="external" href="/library/" target="_blank">Library &amp; Chat</a></li>
							<li class="divider" role="separator"></li>
							<li><a href="{{d:9127896}}"><span class="fa fa-phone" aria-hidden="true"><span class="sr-only">Directory</span></span> Faculty &amp; Staff Directory</a></li>
							<li><a href="/campus-guide/program-directory/default.htm"><span class="fa fa-sitemap" aria-hidden="true"><span class="sr-only">Sitemap</span></span> Programs and Services Directory</a></li>
							<li><a href="https://cerritos.onbio-key.com/"><span class="fas fa-sign-in-alt" aria-hidden="true"><span class="sr-only">Cerritos Portal</span></span> Cerritos Portal</a></li>
							<li><a href="http://www.cerritos.edu/calendar/"><span class="fa fa-calendar" aria-hidden="true"><span class="sr-only">Calendar</span></span> Calendar</a></li>
							<li><a href="/campus-guide/"><span class="fa fa-map" aria-hidden="true"><span class="sr-only">Map</span></span> Campus Map</a></li>
							<li><a href="/agrr"><span class="fas fa-restroom" aria-hidden="true"><span class="sr-only">All Gender Restroom Map</span></span> All Gender Restroom Map</a></li>
							<li><a href="/parking/"><span class="fas fa-parking" aria-hidden="true"><span class="sr-only">Parking</span></span> Parking</a></li>
							<li><a href="{{d:9121100}}"><span class="fas fa-taxi" aria-hidden="true"><span class="sr-only">Safety</span></span> Campus Safety</a></li>
						</ul>
					</li>
					<li id="button-apply"><a class="apply-now" href="http://www.cerritos.edu/apply" target="_blank">Apply Now</a></li>
					<li id="button-give"><a href="http://cerritoscf.org/" target="_blank" class="give"><!--<span class="fa fa-gift" aria-hidden="true"><span class="sr-only">Give</span></span>-->Give</a></li>
				</ul>
			</div>
		</div>


		<div class="container">
			<div class="navbar-header">
				<h1>Cerritos College<a class="navbar-brand logo" href="{{d:9116620}}"><img title="Cerritos College, Norwalk California" src="{{f:80150947}}" alt="Cerritos College, Norwalk California" /></a></h1>
				
				
				<ul class="mobile mobile-quicklinks">
					<li><a href="/campus-guide/abc-index.htm"> <span class="big">A-Z</span> <span class="small">Index</span> </a></li>
					<li><a href="{{d:9127896}}" title="Directory"><span class="fa fa-phone" aria-hidden="true"><span class="sr-only">Directory</span></span></a></li>
					<li><a href="http://www.cerritos.edu/calendar/" title="Calendar"><span class="fa fa-calendar" aria-hidden="true"><span class="sr-only">Calendar</span></span></a></li>
					<li class="dropdown search"><a class="dropdown-toggle" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" title="Search"><span class="fa fa-search" aria-hidden="true"><span class="sr-only">Search</span></span></a>
						<ul class="dropdown-menu">
							<li>

								<!--<form id="searchForm" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
<div class="form-group">
<input class="form-control" placeholder="Search" name="q" id="q" aria-lable="search" type="text">
</div>
</form>--> <!--Mobile Search--> <!--
<script>

(function() {
var cx = '008525147052714186440:tkcmuqghz4s';
var gcse = document.createElement('script');
gcse.type = 'text/javascript';
gcse.async = true;
gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(gcse, s);
})();


</script>
<gcse:searchbox-only resultsUrl="/campus-guide/search.htm"></gcse:searchbox-only>
-->

								<div class="w-form form-wrapper"><form id="searchbox-mobile" action="/campus-guide/search.htm" method="get" name="cse"><input type="hidden" value="your-008525147052714186440:tkcmuqghz4s" name="cx" /> <input type="hidden" value="utf-8" name="ie" /> <input type="hidden" value="en" name="hl" /> <label for="q-mobile">Search:&nbsp;</label><input id="q-mobile" type="text" name="q" /> <input type="submit" value="Go" name="sa" /></form></div>
							</li>
						</ul>
					</li>
				</ul>




				<ul class="mobile mobile-quicklinks dropdown">
					<li class="dropdown quick-links"><a class="dropdown-toggle" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown">Quick Links </a>
						<ul class="dropdown-menu">
							<li><a class="external" href="https://cerritos.onbio-key.com/" target="_blank">MyCerritos</a></li>
							<li><a class="external" href="http://www.cerritos.edu/canvas/" target="_blank">Canvas</a></li>
							<li><a href="https://go.boarddocs.com/ca/cerritos/Board.nsf/Public" target="_blank">BoardDocs</a></li>
							<li><a href="/campus-guide/academic-calendar.htm">Academic Calendar</a></li>
							<li><a href="https://www.cerritos.edu/admissions-and-records/catalogue-schedule/default.htm">Catalog &amp; Schedule</a></li>
							<li><a class="external" href="http://www.cerritos.edu/schedule/" target="_blank">Schedule Plus</a></li>
							<li><a class="external" href="https://www.bkstr.com/cerritosstore/home/en" target="_blank">Bookstore</a></li>
							<li><a class="external" href="/library/" target="_blank">Library &amp; Chat</a></li>
							<li class="divider" role="separator"></li>
							<li><a href="{{d:9127896}}"><span class="fa fa-phone" aria-hidden="true"><span class="sr-only">Directory</span></span> Faculty &amp; Staff Directory</a></li>
							<li><a href="/campus-guide/program-directory/default.htm"><span class="fa fa-sitemap" aria-hidden="true"><span class="sr-only">Sitemap</span></span> Programs and Services Directory</a></li>
							<li><a href="https://cerritos.onbio-key.com/"><span class="fas fa-sign-in-alt" aria-hidden="true"><span class="sr-only">Cerritos Portal</span></span> Cerritos Portal</a></li>
							<li><a href="http://www.cerritos.edu/calendar/"><span class="fa fa-calendar" aria-hidden="true"><span class="sr-only">Calendar</span></span> Calendar</a></li>
							<li><a href="/campus-guide/"><span class="fa fa-map" aria-hidden="true"><span class="sr-only">Map</span></span> Campus Map</a></li>
							<li><a href="/agrr"><span class="fas fa-restroom" aria-hidden="true"><span class="sr-only">All Gender Restroom Map</span></span> All Gender Restroom Map</a></li>
							<li><a href="/parking/"><span class="fas fa-parking" aria-hidden="true"><span class="sr-only">Parking</span></span> Parking</a></li>
							<li><a href="{{d:9121100}}"><span class="fas fa-taxi" aria-hidden="true"><span class="sr-only">Safety</span></span> Campus Safety</a></li>
						</ul>
					</li>
				</ul>
				<a class="navbar-toggle" role="button" href="#siteNavigation" data-target="#siteNavigation">
					<div class="bars"></div>
					<div class="text">Menu</div>
				</a></div>
			<div id="siteNavigation" class="siteNavigation"><a class="menuClose visible-md visible-sm visible-xs" href="#"><span class="sr-only">Close</span></a>
				<ul class="nav navbar-nav main-nav">
					<li id="button-apply-2" class="hidden-lg"><a class="apply-now" href="http://www.cerritos.edu/apply" target="_blank">Apply Now</a></li>
					<li class="hidden-lg"><a class="apply-now" href="http://cerritoscf.org/" target="_blank">Make a Gift</a></li>
					<li><a href="/about/default.htm">About</a></li>
					<li><a href="/_archive/admissions-and-aid/admission-and-aid.htm">Admissions &amp; Aid</a></li>
					<li><a href="/academics/default.htm">Academics</a></li>
					<li><a href="{{f:80134189}}">Services &amp; Support </a></li>
					<li><a href="/caring-campus/default.htm"><span class="fa fa-heart" aria-hidden="true"></span> We Care</a></li>
					<li class="hidden-lg audience-mobile"><a href="/get-started/default.htm">Future Students</a></li>
					<li class="hidden-lg audience-mobile"><a href="{{f:80147106}}">Current Students</a></li>
					<li class="hidden-lg audience-mobile"><a href="{{f:80267046}}">Faculty &amp; Staff</a></li>
					<li class="hidden-lg audience-mobile"><a href="{{f:80270022}}">Community</a></li>
					<li class="dropdown search"><a class="dropdown-toggle" role="button" href="#" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown"> <span class="fa fa-search" aria-hidden="true"><span class="sr-only">Search</span></span></a>
						<ul class="dropdown-menu">
							<li><!--<form id="searchForm-2" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
<div class="form-group">
<input name="q-2" id="q-2" class="form-control" placeholder="Search" aria-lable="search" type="text">
</div>
</form>
--> <!--
<script>
function() {
var cx = '008525147052714186440:tkcmuqghz4s';
var gcse = document.createElement('script');
gcse.type = 'text/javascript';
gcse.async = true;
gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(gcse, s);
}();
</script>
<gcse:searchbox-only resultsUrl="/campus-guide/search.htm"></gcse:searchbox-only>
-->
								<div class="w-form form-wrapper"><form id="searchbox-desktop" action="/campus-guide/search.htm" method="get" name="cse"><input type="hidden" value="your-008525147052714186440:tkcmuqghz4s" name="cx" /> <input type="hidden" value="utf-8" name="ie" /> <input type="hidden" value="en" name="hl" /> <label for="q-desktop">Search Site:&nbsp;</label><input id="q-desktop" type="text" name="q" /> <input type="submit" value="Go" name="sa" /></form></div>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav></div>
<!--#include virtual="/ou-alerts/alerts-config.css.html" -->