<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,user-scalable = yes,initial-scale = 1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">      
<meta name="copyright" content="Cerritos College">
<link rel="alternate" type="application/rss+xml" title="Cerritos College News RSS 2.0" href="https://www.cerritos.edu/_resources/rss/newsroom.xml" />
<link rel="shortcut icon" href="/_resources/images/icons/favicon.ico" type="image/x-icon">
<link rel="icon" href="/_resources/images/icons/favicon.ico" type="image/x-icon">

<!--#include virtual="/_resources/includes/css.inc" -->
<!--#include virtual="/_resources/includes/scripts-head.inc" -->