      

<meta charset="UTF-8">
      <meta name="viewport" content="width=device-width,user-scalable = yes,initial-scale = 1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">      
      <meta name="copyright" content="Cerritos College">
	  <meta name="robots" content="follow, all" />


	  <meta http-equiv="Content-Security-Policy" content="
														  
			script-src-elem *.cerritos.edu *.fontawesome.com *.sharethis.com *.rlets.com *.hotjar.com *.google.com *.gstatic.com 'sha256-S/f473455+gTIwSEeQmK3A2vmTB1ZsFUUW8qIXV9PAY=' *.googleapis.com 'sha256-hY11lFENid8GSRZACOQIVExy8TqE6NSs3qKcwYCbEbY=' 'sha256-UlhZahmvTytinIh9ZV9YIUnu4Hvr0s1u5CSuEUYryq4=' *.bing.com *.facebook.net *.googletagmanager.com *.simpli.fi 'sha256-RLy6t8Uzo7yhtP2BlXRwJviNDmwjt47Njo54HHuR8PE=' 'sha256-GMDREuNQNJynOQvCXFCl/JLp3JtjQWFHx+V4UdEFI34=' sc-static.net googleads.g.doubleclick.net tr.snapchat.com;

			script-src 'self' https://cdn.rlets.com  https://bat.bing.com https://pubads.g.doubleclick.net https://beacon.krxd.net https://ssl.google-analytics.com https://tag.simpli.fi https://i.simpli.fi https://connect.facebook.net https://www.googleadservices.com https://www.googletagmanager.com https://pixel.mathtag.com https://reachlocal.thinkingchat.com https://eu.thinkingchat.com https://www.reachlocallivechat.com;
														  
			connect-src 'self' *.fontawesome.com *.sharethis.com *.google-analytics.com *.rlets.com *.ocelotbot.com *.googleapis.com *.liqadprdct-capture-prod-east.gannettdigital.com https://capture-api.reachlocalservices.com/originCountry https://liqadprdct-capture-prod-east.gannettdigital.com/capture_logger/api/v1/insights https://apgb2b-reachcodeandproxy.gannettdigital.com https://*.rlets.com https://capture-api.reachlocalservices.com https://um.simpli.fi *.google.com *.snapchat.com https://capturelogger-prod-usa.localiq.com;
														  
		  img-src 'self' *.facebook.com *.google.com *.bing.com *.ocelotbot.com *.gstatic.com *.googleapis.com *.sharethis.com https://fault.rlets.com;
														  
		style-src 'self' *.fontawesome.com 'sha256-ZL58hL5KbUHBRnMK797rN7IR+Tg9Aw61ddJ/rmxn1KM=' 'sha256-bepHRYpM181zEsx4ClPGLgyLPMyNCxPBrA6m49/Ozqg=' 'sha256-uCITVBkyNmwuSQXzSNUuRx7G7+1kS2zWJ9SjHF0W2QA=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-/iTtprHq4pmAtIqHNFE9pbvgB7i9+WHUDiqe9wWTmFg=' 'sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog=' 'sha256-S808OWJL90pFKx8qBHkwxQM8bB3z9ho1pLkDSj46E18=' *.gstatic.com *.ocelotbot.com *.googleapis.com 'sha256-/Q4se7FLGCaPFRdiDgb/uQcgnY12w7eKaV8TA9b4SEc=' 'sha256-/Q4se7FLGCaPFRdiDgb/uQcgnY12w7eKaV8TA9b4SEc=' *.rlets.com 'sha256-tscZqskB5o8GQvy+Z0l+MUN5Rsa/ILeBWgN7PYTWzKc=' 'sha256-MFjEbgpqdzRYPoxO6b/tEkYEd6dJCX7mVLZPyae+z5I=' 'sha256-61GP5oOB6AM4kSgw8lIMYfhMj41kKvLhjgBtZROJi8k=' 'sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog='
														  
		;


														  
														  
														  "/>


	  <link rel="alternate" type="application/rss+xml" title="Cerritos College News RSS 2.0" href="https://www.cerritos.edu/_resources/rss/newsroom.xml" />
      <link rel="shortcut icon" href="{{f:80150578}}" type="image/x-icon">
      <link rel="icon" href="{{f:80150578}}" type="image/x-icon">
	  
    <link rel="stylesheet" href="{{f:80151040}}"/>
<!-- Link to font awesome set for TikTok font -->
<script src="https://kit.fontawesome.com/5722ff1f59.js" crossorigin="anonymous"></script>
<!-- Link to latest font awesome set 5.6.3 added by Samuel for newer icon sets on the SEM division home page --> 
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<!-- Legacy font awesome set -->
    <link rel="stylesheet" href="{{f:80148375}}">


	<link rel="stylesheet" href="{{f:80148352}}">
	<link rel="stylesheet" href="{{f:80148402}}">
<!--     <link rel="stylesheet" href="/_resources/css/flexslider.min.css" type="text/css"/> -->
	<link rel="stylesheet" href="{{f:80151085}}" type="text/css">
    <link rel="stylesheet" href="{{f:80151090}}?v=15"/>
	<link rel="stylesheet" href="{{f:80151086}}">
<link rel="stylesheet" href="{{f:80151096}}">
	<link rel="stylesheet" href="{{f:80151058}}?v=1"/>
<link rel="stylesheet" href="{{f:80151063}}"/> 

	<!-- IE Conditionals from current Cerritos.edu site -->
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="{{f:80151045}}" type="text/javascript">
          //comment
        </script>
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- [if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	  <![endif] -->
 	<!--[if lt IE 8]>
	<link href="/_resources/css/css2_tables_min.css" rel="stylesheet" type="text/css" media="all" />
        <![endif]-->
	<!-- End Conditionals -->
	
    <script src="{{f:80151168}}"></script>
<!-- <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script> -->
    <script src="{{f:80151043}}"></script>
    <script src="{{f:80151164}}"></script>
	<script src="{{f:80151169}}"></script>
	<script src="{{f:80151144}}"></script>
	
	
	
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58dc7d749801000011c55022&product=inline-share-buttons"></script>

<!-- <script type="text/javascript" src="//cdn.rlets.com/capture_configs/a22/6ab/1a9/2004c9ba5048543548e660b.js" async="async"></script> -->
<!-- <script type="text/javascript" src="////cdn.rlets.com/capture_configs/a22/6ab/1a9/2004c9ba5048543548e660b.js" async="async"></script>  -->
<script type="text/javascript" src="//cdn.rlets.com/capture_configs/a22/6ab/1a9/2004c9ba5048543548e660b.js" async="async"></script>

<!-- Global site tag (gtag.js) - Google Ads: 465189990 --> 
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=AW-465189990"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
 
  gtag('config', 'AW-465189990');
</script> -->

<!-- Hotjar Tracking Code for https://www.cerritos.edu -->
<!-- <script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2684053,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script> -->

<!-- Google tag (gtag.js) -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=G-23NZF7NKJF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-23NZF7NKJF');
</script> -->

<!-- Hotjar and Google Tag functions combined in external JS file 5/18/23 schavez -->
<script type="text/javascript" src="{{f:80151148}}"></script>