     <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width,user-scalable = yes,initial-scale = 1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">      
      <meta name="copyright" content="Cerritos College">
	  <meta name="robots" content="all" />
      <link rel="shortcut icon" href="{{f:80150566}}" type="image/x-icon">
      <link rel="icon" href="{{f:80150566}}" type="image/x-icon">


    <link rel="stylesheet" href="{{f:80151040}}"/>
<!-- Link to latest font awesome set 5.6.3 added by Samuel for newer icon sets on the SEM division home page --> 
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<!-- Legacy font awesome set -->
    <link rel="stylesheet" href="{{f:80148375}}">


	<link rel="stylesheet" href="{{f:80148352}}">
	<link rel="stylesheet" href="{{f:80148402}}">
<!--     <link rel="stylesheet" href="/_resources/css/flexslider.min.css" type="text/css"/> -->
	<link rel="stylesheet" href="{{f:80151085}}" type="text/css">
    <link rel="stylesheet" href="{{f:80151090}}"/>
	<link rel="stylesheet" href="{{f:80151086}}">
<link rel="stylesheet" href="{{f:80151096}}">
	<link rel="stylesheet" href="{{f:80151058}}"/>
    <link media="all" rel="stylesheet" href="{{f:80151079}}" />
	
	<!-- IE Conditionals from current Cerritos.edu site -->
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="{{f:80151045}}" type="text/javascript">
          //comment
        </script>
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- [if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	  <![endif] -->
 	<!--[if lt IE 8]>
	<link href="/_resources/css/css2_tables_min.css" rel="stylesheet" type="text/css" media="all" />
        <![endif]-->
	<!-- End Conditionals -->
	
    <script src="{{f:80151168}}"></script>
    <script src="{{f:80151043}}"></script>
    <script src="{{f:80151164}}"></script>
	<script src="{{f:80151169}}"></script>
	<script src="{{f:80151144}}"></script>
<script src="{{f:80151161}}"></script>
	
	
	
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58dc7d749801000011c55022&product=inline-share-buttons"></script>



