<nav class="accessibility" id="accessibility">
     <a href="#skiptocontent">Skip to main content</a>
</nav>
<div id="headerDiv">
    <nav class="navbar navbar-default">
		<div class="top-bar">
			<div class="container">
				   <ul class="nav navbar-nav audience" id="nav-audience">
					<li><a href="/get-started/default.htm">Future Students</a></li>
					<li><a href="{{f:80147106}}">Current Students</a></li>
					<li><a href="{{f:80267046}}">Faculty &amp; Staff</a></li>
					<li><a href="{{f:80270022}}">Community</a></li>
        			</ul>
    <ul class="nav navbar-nav navbar-right quick-nav" id="quick-links">
				<li class="a-z-index"><a href="/campus-guide/abc-index.htm">A-Z Index</a></li>
                <li class="dropdown quick-links">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Quick Links <span class="fa fa-caret-down fa-lg"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="http://my.cerritos.edu/" class="external" target="_blank">MyCerritos</a></li>
						<li><a href="http://www.cerritos.edu/canvas/" class="external" target="_blank">Canvas</a></li>
						<li><a href="/campus-guide/academic-calendar.htm">Important Dates &amp; Deadlines</a></li>
						<li><a href="https://www.cerritos.edu/admissions-and-records/catalogue-schedule/default.htm">Catalog &amp; Schedule</a></li>
						<li><a href="http://www.cerritos.edu/schedule/" class="external" target="_blank">Schedule Plus</a></li>
						<li><a href="https://www.bkstr.com/cerritosstore/home/en" class="external" target="_blank">Bookstore</a></li>
						<li><a href="http://cert.ent.sirsi.net/client/en_US/cerritos/" class="external" target="_blank">Library</a></li>
                        <li class="divider" role="separator"></li>
                        <li><a href="{{d:9127896}}"><span aria-hidden="true" class="fa fa-phone"><span class="sr-only">Directory</span></span> Directory</a></li>
                        <li><a href="http://www.cerritos.edu/calendar/"><span aria-hidden="true" class="fa fa-calendar"><span class="sr-only">Calendar</span></span> Calendar</a></li>
						<li><a href="/campus-guide/"><span aria-hidden="true" class="fa fa-map"><span class="sr-only">Map</span></span> Campus Map</a></li>
                    </ul>
                </li>
                <li id="button-apply">
                    <a class="apply-now" href="http://www.cerritos.edu/apply" target="_blank">Apply Now</a>
                </li>
		 <li class="give">
                    <a href="http://cerritoscf.org/" target="_blank"><span class="fa fa-gift" aria-hidden="true"><span class="sr-only">Give</span></span></a>
                </li>
            </ul>
			</div>
		</div>
    <div class="container">
        <div class="navbar-header">
            <h1>Cerritos College<a class="navbar-brand logo" href="{{d:9116620}}"><img alt="Cerritos College, Norwalk California" title="Cerritos College, Norwalk California" src="{{f:80150930}}"></a></h1>
            <ul class="mobile mobile-quicklinks">
                <li>
                    <a href="/campus-guide/abc-index.htm">
                        <span class="big">A-Z</span> <span class="small">Index</span>
                    </a>
                </li>
                <li>
                    <a href="{{d:9127896}}"><span aria-hidden="true" class="fa fa-phone"><span class="sr-only">Directory</span></span></a>
                </li>
                <li>
                    <a href="http://www.cerritos.edu/calendar/"><span aria-hidden="true" class="fa fa-calendar"><span class="sr-only">Calendar</span></span></a>
                </li>
                <li class="dropdown search">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"><span aria-hidden="true" class="fa fa-search"><span class="sr-only">Search</span></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <!--<form id="searchForm" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
                                <div class="form-group">
                                    <input class="form-control" placeholder="Search" name="q" id="q" aria-lable="search" type="text">
                                </div>
                            </form>-->
					<!--Mobile Search-->
<!--
							<script>

  (function() {
    var cx = '008525147052714186440:tkcmuqghz4s';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
							

</script>
<gcse:searchbox-only resultsUrl="/campus-guide/search.htm"></gcse:searchbox-only>
-->
							
							<div class="w-form form-wrapper"><form id="searchbox-mobile" action="/campus-guide/search.htm" method="get" name="cse"><input name="cx" type="hidden" value="your-008525147052714186440:tkcmuqghz4s" /> <input name="ie" type="hidden" value="utf-8" /> <input name="hl" type="hidden" value="en" /> 
	
	<label for="q-mobile">Search:&nbsp;</label><input name="q" id="q-mobile" type="text" />
	
	<input name="sa" type="submit" value="Go" /></form></div>
							
							
                        </li>
                    </ul>
                </li>
            </ul>
			<ul class="mobile mobile-quicklinks dropdown">
                <li class="dropdown quick-links">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Quick Links <span class="fa fa-caret-down fa-lg"></span></a>
                    <ul class="dropdown-menu">
						<li><a href="http://my.cerritos.edu/" class="external" target="_blank">MyCerritos</a></li>
						<li><a href="http://www.cerritos.edu/canvas/" class="external" target="_blank">Canvas</a></li>
						<li><a href="/campus-guide/academic-calendar.htm">Important Dates &amp; Deadlines</a></li>
						<li><a href="https://www.cerritos.edu/admissions-and-records/catalogue-schedule/default.htm">Catalog &amp; Schedule</a></li>
						<li><a href="http://www.cerritos.edu/schedule/" class="external" target="_blank">Schedule Plus</a></li>
						<li><a href="https://www.bkstr.com/cerritosstore/home/en" class="external" target="_blank">Bookstore</a></li>
						<li><a href="http://cert.ent.sirsi.net/client/en_US/cerritos/" class="external" target="_blank">Library</a></li>
                    </ul>
                </li>
            </ul>
            <a class="navbar-toggle" data-target="#siteNavigation" role="button" href="#siteNavigation">
                <div class="bars">
                    <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                </div>
                <div class="text">
                    Menu
                </div>
            </a>
        </div>
		<div class="siteNavigation" id="siteNavigation">
           <a href="#" class="menuClose visible-md visible-sm visible-xs"><span class="fa fa-times" aria-hidden="true"></span><span class="sr-only">Close</span></a>
            <ul class="nav navbar-nav main-nav">
				<li id="button-apply-2" class="hidden-lg"><a class="apply-now" href="http://www.cerritos.edu/apply" target="_blank">Apply Now</a></li>
				<li class="hidden-lg"><a class="apply-now" href="http://cerritoscf.org/" target="_blank">Make a Gift</a></li>
                <li><a href="/about/default.htm">About</a></li>
                <li><a href="/_archive/admissions-and-aid/admission-and-aid.htm">Admissions &amp; Aid</a></li>
                <li><a href="/academics/default.htm">Academics</a></li>
                <li><a href="{{f:80134122}}">Student Life</a></li>
                <li><a href="{{f:80134189}}">Services</a></li>
				<li class="hidden-lg audience-mobile"><a href="/get-started/default.htm">Future Students</a></li>
				<li class="hidden-lg audience-mobile"><a href="{{f:80147106}}">Current Students</a></li>
				<li class="hidden-lg audience-mobile"><a href="{{f:80267046}}">Faculty &amp; Staff</a></li>
				<li class="hidden-lg audience-mobile"><a href="{{f:80270022}}">Community</a></li>
    			<li class="dropdown search">
                    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"><span aria-hidden="true" class="fa fa-search"><span class="sr-only">Search</span></span></a>
                    <ul class="dropdown-menu">
                        <li>
							<!--<form id="searchForm-2" method="get" action="/campus-guide/search.htm" class="navbar-form navbar-left">
                                <div class="form-group">
                                    <input name="q-2" id="q-2" class="form-control" placeholder="Search" aria-lable="search" type="text">
                                </div>
                            </form>
-->
<!--
							<script>
  function() {
    var cx = '008525147052714186440:tkcmuqghz4s';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  }();
</script>
<gcse:searchbox-only resultsUrl="/campus-guide/search.htm"></gcse:searchbox-only>
-->
							
							<div class="w-form form-wrapper"><form id="searchbox-desktop" action="/campus-guide/search.htm" method="get" name="cse"><input name="cx" type="hidden" value="your-008525147052714186440:tkcmuqghz4s" /> <input name="ie" type="hidden" value="utf-8" /> <input name="hl" type="hidden" value="en" /> 
	
	<label for="q-desktop">Search Site:&nbsp;</label><input name="q" id="q-desktop" type="text" />
	
	<input name="sa" type="submit" value="Go" /></form></div>
							
							
							
							
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
		</div>
    </nav>
</div>
