     <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width,user-scalable = yes,initial-scale = 1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">      
      <meta name="copyright" content="Cerritos College">
	  <meta name="robots" content="none" />
<link rel="alternate" type="application/rss+xml" title="Cerritos College News RSS 2.0" href="https://www.cerritos.edu/_resources/rss/newsroom.xml" />
      <link rel="shortcut icon" href="{{f:80150578}}" type="image/x-icon">
      <link rel="icon" href="{{f:80150578}}" type="image/x-icon">
	  
    <link rel="stylesheet" href="{{f:80151040}}"/>
<!-- Link to font awesome set for TikTok font -->
<script src="https://kit.fontawesome.com/5722ff1f59.js" crossorigin="anonymous"></script>
<!-- Link to latest font awesome set 5.6.3 added by Samuel for newer icon sets on the SEM division home page --> 
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<!-- Legacy font awesome set -->
    <link rel="stylesheet" href="{{f:80148375}}">


	<link rel="stylesheet" href="{{f:80148352}}">
	<link rel="stylesheet" href="{{f:80148402}}">
<!--     <link rel="stylesheet" href="/_resources/css/flexslider.min.css" type="text/css"/> -->
	<link rel="stylesheet" href="{{f:80151085}}" type="text/css">
    <link rel="stylesheet" href="{{f:80151090}}?v=15"/>
	<link rel="stylesheet" href="{{f:80151086}}">
<link rel="stylesheet" href="{{f:80151096}}">
	<link rel="stylesheet" href="{{f:80151058}}?v=1"/>
<link rel="stylesheet" href="{{f:80151063}}"/> 

	<!-- IE Conditionals from current Cerritos.edu site -->
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="{{f:80151045}}" type="text/javascript">
          //comment
        </script>
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- [if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	  <![endif] -->
 	<!--[if lt IE 8]>
	<link href="/_resources/css/css2_tables_min.css" rel="stylesheet" type="text/css" media="all" />
        <![endif]-->
	<!-- End Conditionals -->
	
    <script src="{{f:80151168}}"></script>
    <script src="{{f:80151043}}"></script>
    <script src="{{f:80151164}}"></script>
	<script src="{{f:80151169}}"></script>
	<script src="{{f:80151144}}"></script>
	
	
	
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58dc7d749801000011c55022&product=inline-share-buttons"></script>

<script type="text/javascript" src="//cdn.rlets.com/capture_configs/a22/6ab/1a9/2004c9ba5048543548e660b.js" async="async"></script>

<!-- Global site tag (gtag.js) - Google Ads: 465189990 --> 
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-465189990"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
 
  gtag('config', 'AW-465189990');
</script>

<!-- Hotjar Tracking Code for https://www.cerritos.edu -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2684053,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
