     <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width,user-scalable = yes,initial-scale = 1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">      
      <meta name="copyright" content="Cerritos College">
<link rel="alternate" type="application/rss+xml" title="Cerritos College News RSS 2.0" href="https://www.cerritos.edu/_resources/rss/newsroom.xml" />
      <link rel="shortcut icon" href="{{f:80150578}}" type="image/x-icon">
      <link rel="icon" href="{{f:80150578}}" type="image/x-icon">
	  
    <link rel="stylesheet" href="{{f:80151040}}"/><!-- /_resources/framework/bootstrap/css/bootstrap.min.css -->

	<!-- Legacy font awesome set -->
<!-- 	<link rel="stylesheet" href="/_resources/fonts/font-awesome-4.7.0/css/font-awesome.min.css"> -->
	
	<!-- Link to font awesome set for TikTok font -->
<!-- 	<script src="https://kit.fontawesome.com/5722ff1f59.js" crossorigin="anonymous"></script> -->

	<!-- Link to latest font awesome set 5.6.3 added by Samuel for newer icon sets on the SEM division home page --> 
	<!-- 	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
 -->
	<link rel="stylesheet" href="{{f:80148448}}"><!-- /_resources/fonts/fontawesome-free-6.4.2-web/css/all.min.css-->

	<!-- Load fonts from Google Fonts CDN -- 10/27/2023 - Open Sans and Roboto Condensed -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;0,700;0,800;1,400;1,600;1,700;1,800&family=Roboto+Condensed:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" integrity="sha384-aXy2nw69yuCU/EK3wQUs5KpkbNbiB65XesmmtQKdiXF3ZglJMLhVMxOFgu8iZfCF" crossorigin="anonymous">
	
	<!-- Swapped for Google Fonts CDN 10/27/2023 - see above
	/_resources/fonts/Open-Sans/css/fonts.css
	/_resources/fonts/Roboto-Condensed/css/fonts.css
	<link rel="stylesheet" href="/_resources/fonts/Open-Sans/css/fonts.css">
	<link rel="stylesheet" href="/_resources/fonts/Roboto-Condensed/css/fonts.css">
	-->

	<!-- <link rel="stylesheet" href="/_resources/css/flexslider.min.css" type="text/css"/> -->
	<link rel="stylesheet" href="{{f:80151085}}" type="text/css"><!-- /_resources/css/flexslider.css -->
    <link rel="stylesheet" href="{{f:80151090}}?v=15"/><!-- /_resources/css/main-4.css -->
	<link rel="stylesheet" href="{{f:80151086}}"><!-- /_resources/css/owl.carousel.css-->
	<link rel="stylesheet" href="{{f:80151096}}"><!-- /_resources/css/owl.theme.default.min.css -->
	<link rel="stylesheet" href="{{f:80151058}}?v=1"/><!-- /_resources/css/cerritos-legacy.css -->
	<link rel="stylesheet" href="{{f:80151063}}"/><!-- /_resources/css/aos_css_reduced_motion.css  -->
	<link rel="stylesheet" href="{{f:80151089}}"/> <!--/_resources/css/components.css  -->
	<link rel="stylesheet" href="{{f:80151078}}"/> <!--/_resources/css/modern-campus-forms.css  -->

	<!-- IE Conditionals from current Cerritos.edu site -->
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -- removed 11/9/2023 -->
      <!--<script src="/_resources/bootstrap/js/ie10-viewport-bug-workaround.js" type="text/javascript">
          //comment
        </script>-->
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- [if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	  <![endif] -->
 	<!--[if lt IE 8]>
	<link href="/_resources/css/css2_tables_min.css" rel="stylesheet" type="text/css" media="all" />
        <![endif]-->
	<!-- End Conditionals -->
	
    <!-- Replaced with CDN 10/27/2023
	<script src="/_resources/js/jquery.js"></script>
	-->
	<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
	<!--<script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-migrate-3.3.2.min.js"></script>-->
    <script src="{{f:80151043}}"></script>
    <!-- 10/27/2023 Moved flexslider.js, accordion-1.js, cerritos-legacy.js and share this js to footer-->

<!-- Capture Code - Cerritos College Jamie McNinch jamie@gradcomm.com -->
<!-- <script type="text/javascript" src="//cdn.rlets.com/capture_configs/a22/6ab/1a9/2004c9ba5048543548e660b.js" async="async"></script> -->
<!-- Udpdated code 5-25-2023 -->
<!-- <script type="text/javascript" src="////cdn.rlets.com/capture_configs/a22/6ab/1a9/2004c9ba5048543548e660b.js" async="async"></script>  -->
<!-- Moved to Google Tag Manager - June 2023
<script type="text/javascript" src="//cdn.rlets.com/capture_configs/a22/6ab/1a9/2004c9ba5048543548e660b.js" async="async"></script>
-->

<!-- Global site tag (gtag.js) - Google Ads: 465189990 --> 
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=AW-465189990"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
 
  gtag('config', 'AW-465189990');
</script> -->

<!-- Google Tag Manager -- Added June 2023 -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MHSR46S');</script>
<!-- End Google Tag Manager -->

<!-- Google tag (gtag.js) -->
<!-- OLD Univesal Google Analytics Removed June 2023
<script async src="https://www.googletagmanager.com/gtag/js?id=G-23NZF7NKJF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-23NZF7NKJF');
</script>-->
