<nav class="visually-hidden" aria-label="accessibility">
	<a href="#skiptocontent">Skip to main content</a>
</nav>
<div id="navigation">
	<div id="search-panel" class="collapse bg-secondary">
		<div class="container-xl">
			<form class="py-4" id="searchbox-panel" action="/campus-guide/search.htm" method="get" name="cse">
				<input name="cx" type="hidden" value="your-008525147052714186440:tkcmuqghz4s" />
				<input name="ie" type="hidden" value="utf-8" />
				<input name="hl" type="hidden" value="en" />
				<div class="row g-3 align-items-center">
					<div class="col-12 col-md">
						<label class="form-label visually-hidden" for="q-panel">Search Site</label>
						<input class="form-control form-control-lg" id="q-panel" name="q" type="text" placeholder="Enter your search..." />
					</div>
					<div class="col-12 col-md-auto">
						<input class="btn btn-primary w-100" name="sa" type="submit" value="Search" />
					</div>
				</div>
			</form>
		</div>
	</div>

	<div class="container-xl py-3">
		<div class="row">
			<div class="col">
				<div class="d-flex align-items-center justify-content-between">
					<div class="logo">
						<a href="/">
							<span class="visually-hidden">Cerritos College Home</span>
							<img src="/_resources/images/2026/cerritos-logo-white.svg" class="d-none d-lg-block" alt="Cerritos College Logo" />
							<img src="/_resources/images/2026/cerritos-logo-white-mobile.svg" class="d-block d-lg-none" alt="Cerritos College Logo" />
						</a>
					</div>
					<nav class="primary-nav d-flex justify-content-end align-items-center">
						<a href="" class="btn btn-primary">Apply <span class="d-none d-lg-inline">Now</span></a>
						<button class="btn btn-transparent btn-white btn-circle" id="search-panel-toggle" type="button" data-bs-toggle="collapse" data-bs-target="#search-panel" aria-expanded="false" aria-controls="search-panel">
							<span class="visually-hidden">Search</span>
							<span class="fa-sharp fa-regular fa-search-plus" aria-hidden="true"></span>
						</button>
						<button class="btn btn-transparent btn-white btn-circle" id="main-nav-panel-toggle" type="button" aria-expanded="false" aria-controls="main-nav-panel">
							<span class="visually-hidden">Open Main Navigation Menu</span>
							<span class="main-nav-toggle-icon" aria-hidden="true">
								<span class="main-nav-toggle-icon__bar"></span>
								<span class="main-nav-toggle-icon__bar"></span>
								<span class="main-nav-toggle-icon__bar"></span>
							</span>
						</button>
					</nav>
				</div>
			</div>
		</div>
	</div>

	<div id="main-nav-panel">
		<div class="container-xl">
			<div class="row">
				<div class="col-12 col-md-6">
					Left Nav
				</div>
				<div class="col-12 col-md-6">
					Right Nav
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container-xl mt-5 mb-3">
	<div class="row">
		<div class="col-12">
			<h1 class="text-white">Financial Aid</h1>
		</div>
	</div>
</div>

<!--#include virtual="/ou-alerts/alerts-config.css.html" -->
