
     <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width,user-scalable = yes,initial-scale = 1.0" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />      
      <meta name="author" content="tbowman" />
      <meta name="copyright" content="Cerritos College" />
      <meta name="description" content="[page-title]: Cerritos College is a public comprehensive community college located in Norwalk, California, offering degrees and certificates in 87 areas of 
study in nine divisions." />
      <meta name="keywords" content="[page-title], Cerritos College" />
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      <link rel="icon" href="/favicon.ico" type="image/x-icon" />

<!-- These meta tags were found in the current Cerritos web page head, and may be useful:
      <meta http-equiv="cache-control" content="text/html;no-cache" />
      <meta http-equiv="expires" content="text/html;-1" />
      <meta http-equiv="pragma" content="text/html;no-cache" />
      <meta http-equiv="Content-Script-Type" content="text/html;text/JavaScript" />
      <meta http-equiv="Content-Style-Type" content="text/html;text/css" /> -->
	  
    <!--<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet" />-->
    <link rel="stylesheet" href="{{f:80151040}}"/>
    <link rel="stylesheet" href="{{f:80148375}}">
	<link rel="stylesheet" href="{{f:80148352}}">
	<link rel="stylesheet" href="{{f:80148402}}">
<!--     <link rel="stylesheet" href="/_resources/css/flexslider.min.css" type="text/css"/> -->
	<link rel="stylesheet" href="{{f:80151085}}" type="text/css">
    <link rel="stylesheet" href="{{f:80151090}}"/>
	<link rel="stylesheet" href="{{f:80151058}}"/>
	 <title>Cerritos College | [page-title]</title>
	
	<!-- IE Conditionals from current Cerritos.edu site -->
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="{{f:80151045}}" type="text/javascript">
          //comment
        </script>
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- [if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	  <![endif] -->
 	<!--[if lt IE 8]>
	<link href="/_resources/css/css2_tables_min.css" rel="stylesheet" type="text/css" media="all" />
        <![endif]-->
	<!-- End Conditionals -->
	
	
    <script src="{{f:80151168}}"></script>
    <script src="{{f:80151043}}"></script>
    <script src="{{f:80151164}}"></script>
    <script src="{{f:80151147}}"></script>
    <script src="{{f:80151171}}"></script>
    <script src="{{f:80151160}}"></script>
	
	<script type="text/javascript">
		$(document).ready(function(){
    		$(".close-icon").click(function(){
       		 $("#emergencyNotice").hide(750);
    		});
		});
	</script>
    
	
	<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58dc7d749801000011c55022&product=inline-share-buttons"></script>


