<div id="photoDivNew" class="flexslider">
<div id="dlink"><a title="header photo descriptions" onclick="trackOutboundLink('https://www.cerritos.edu/default-sliders-d-link.htm'); return false;" href="/_resources/includes/default-sliders-d-link.pcf">d</a></div>
<ul class="slides">
<li><img title="Slide" src="{{f:80150699}}" alt="Slide" width="1300" height="600" longdesc="https://www.cerritos.edu/default-sliders-d-link.htm" />
<div class="slide-content">
<h4>ONE CAMPUS FOR ALL</h4>
<h3>INCLUSIVE AND DIVERSE</h3>
<a class="button" href="#">REVIEW OUR DIVERSITY PROGRAM</a></div>
</li>
<li><img title="Slide" src="{{f:80150800}}" alt="Slide" width="1300" height="600" longdesc="https://www.cerritos.edu/default-sliders-d-link.htm" />
<div class="slide-content">
<h4>A California Promise Program</h4>
<h3>Cerritos Complete</h3>
<a class="button" href="#">1st Year of College FREE</a></div>
</li>
<li><img title="Slide" src="{{f:80150861}}" alt="Slide" width="1300" height="600" longdesc="https://www.cerritos.edu/default-sliders-d-link.htm" />
<div class="slide-content">
<h4>ONE CAMPUS FOR ALL</h4>
<h3>INCLUSIVITY</h3>
<a class="button" href="#">REVIEW OUR DIVERSITY PROGRAM</a></div>
</li>
</ul>
</div>
