<script src="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/ScrollTrigger.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/ScrollSmoother.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/ScrollToPlugin.min.js"></script>
<script src="/_resources/js/flexslider.js"></script>
<script src="/_resources/js/accordion-1.js"></script>
<script src="/_resources/js/cerritos-legacy.js"></script>
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58dc7d749801000011c55022&product=inline-share-buttons"></script>

<!-- mailto script added 2025 -->
<script src="/_resources/js/mailto.js"></script>
